<?php

namespace Database\Seeders;

use App\Models\SubSubCategory;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SubSubCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table("sub_sub_categories")->delete();

        $defaultData =
            [
                [
                    "id" => "1",
                    "name" => "Dış Giyim",
                    "sub_category_id" => "1",
                    "seo_link" => "dis-giyim",
                    "seo_title" => "Dış Giyim",
                    "seo_description" => "Dış Giyim kategorisi için açıklama",
                    "seo_keywords" => "Dış Giyim, giyim, moda",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "2",
                    "name" => "Blazer Ceket",
                    "sub_category_id" => "1",
                    "seo_link" => "blazer-ceket",
                    "seo_title" => "Blazer Ceket",
                    "seo_description" => "Blazer ceketler için açıklama",
                    "seo_keywords" => "Blazer Ceket, moda, giyim",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "3",
                    "name" => "Takım Elbise",
                    "sub_category_id" => "1",
                    "seo_link" => "takim-elbise",
                    "seo_title" => "Takım Elbise",
                    "seo_description" => "Takım elbiseler için açıklama",
                    "seo_keywords" => "Takım Elbise, moda, giyim",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "4",
                    "name" => "Elbise & Tulum",
                    "sub_category_id" => "2",
                    "seo_link" => "elbise-tulum",
                    "seo_title" => "Elbise & Tulum",
                    "seo_description" => "Elbiseler ve tulumlar için açıklama",
                    "seo_keywords" => "Elbise, Tulum, moda, giyim",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "5",
                    "name" => "Gömlek & Bluz",
                    "sub_category_id" => "2",
                    "seo_link" => "gomlek-bluz",
                    "seo_title" => "Gömlek & Bluz",
                    "seo_description" => "Gömlekler ve bluzlar için açıklama",
                    "seo_keywords" => "Gömlek, Bluz, moda, giyim",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "6",
                    "name" => "Gömlek",
                    "sub_category_id" => "1",
                    "seo_link" => "gomlek",
                    "seo_title" => "Gömlek",
                    "seo_description" => "Gömlekler için açıklama",
                    "seo_keywords" => "Gömlek, moda, giyim",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "7",
                    "name" => "Tişört & Atlet",
                    "sub_category_id" => "1",
                    "seo_link" => "tisort-atlet",
                    "seo_title" => "Tişört & Atlet",
                    "seo_description" => "Tişörtler ve atletler için açıklama",
                    "seo_keywords" => "Tişört, Atlet, moda, giyim",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "8",
                    "name" => "Erkek Ayakkabı",
                    "sub_category_id" => "3",
                    "seo_link" => "erkek-ayakkabi",
                    "seo_title" => "Erkek Ayakkabı",
                    "seo_description" => "Erkek ayakkabıları için açıklama",
                    "seo_keywords" => "Erkek Ayakkabı, moda, giyim",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "9",
                    "name" => "Kadın Ayakkabı",
                    "sub_category_id" => "3",
                    "seo_link" => "kadin-ayakkabi",
                    "seo_title" => "Kadın Ayakkabı",
                    "seo_description" => "Kadın ayakkabıları için açıklama",
                    "seo_keywords" => "Kadın Ayakkabı, moda, giyim",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "10",
                    "name" => "Pantolon & Şort",
                    "sub_category_id" => "1",
                    "seo_link" => "pantolon-sort",
                    "seo_title" => "Pantolon & Şort",
                    "seo_description" => "Pantolonlar ve şortlar için açıklama",
                    "seo_keywords" => "Pantolon, Şort, moda, giyim",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "11",
                    "name" => "Kız Çocuk",
                    "sub_category_id" => "4",
                    "seo_link" => "kiz-cocuk",
                    "seo_title" => "Kız Çocuk",
                    "seo_description" => "Kız çocuk giyim için açıklama",
                    "seo_keywords" => "Kız Çocuk, moda, giyim",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "12",
                    "name" => "Erkek Çocuk",
                    "sub_category_id" => "4",
                    "seo_link" => "erkek-cocuk",
                    "seo_title" => "Erkek Çocuk",
                    "seo_description" => "Erkek çocuk giyim için açıklama",
                    "seo_keywords" => "Erkek Çocuk, moda, giyim",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "13",
                    "name" => "Aksesuar",
                    "sub_category_id" => "4",
                    "seo_link" => "aksesuar",
                    "seo_title" => "Aksesuar",
                    "seo_description" => "Moda aksesuarları için açıklama",
                    "seo_keywords" => "Aksesuar, moda, giyim",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "14",
                    "name" => "Kadın Güneş Gözlüğü",
                    "sub_category_id" => "5",
                    "seo_link" => "kadin-gunes-gozlugu",
                    "seo_title" => "Kadın Güneş Gözlüğü",
                    "seo_description" => "Şık kadın güneş gözlükleri için açıklama",
                    "seo_keywords" => "Kadın Güneş Gözlüğü, moda, güneş gözlükleri",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "15",
                    "name" => "Erkek Güneş Gözlüğü",
                    "sub_category_id" => "5",
                    "seo_link" => "erkek-gunes-gozlugu",
                    "seo_title" => "Erkek Güneş Gözlüğü",
                    "seo_description" => "Şık erkek güneş gözlükleri için açıklama",
                    "seo_keywords" => "Erkek Güneş Gözlüğü, moda, güneş gözlükleri",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "16",
                    "name" => "Eşofman & Sweatshirt",
                    "sub_category_id" => "1",
                    "seo_link" => "esofman-sweatshirt",
                    "seo_title" => "Eşofman & Sweatshirt",
                    "seo_description" => "Rahat eşofman ve sweatshirtler için açıklama",
                    "seo_keywords" => "Eşofman, Sweatshirt, moda, giyim",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "17",
                    "name" => "İş Elbiseleri",
                    "sub_category_id" => "1",
                    "seo_link" => "is-elbiseleri",
                    "seo_title" => "İş Elbiseleri",
                    "seo_description" => "Şık iş elbiseleri için açıklama",
                    "seo_keywords" => "İş Elbiseleri, moda, giyim",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "18",
                    "name" => "İç Giyim & Uyku Giyim",
                    "sub_category_id" => "1",
                    "seo_link" => "ic-giyim-uyku-giyim",
                    "seo_title" => "İç Giyim & Uyku Giyim",
                    "seo_description" => "Rahat iç giyim ve uyku giyim ürünleri için açıklama",
                    "seo_keywords" => "İç Giyim, Uyku Giyim, moda, giyim",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "19",
                    "name" => "Aksesuarlar",
                    "sub_category_id" => "1",
                    "seo_link" => "aksesuarlar",
                    "seo_title" => "Aksesuarlar",
                    "seo_description" => "Şık aksesuarlar için açıklama",
                    "seo_keywords" => "Aksesuarlar, moda, takı, şapka",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "20",
                    "name" => "Büyük Beden",
                    "sub_category_id" => "1",
                    "seo_link" => "buyuk-beden",
                    "seo_title" => "Büyük Beden",
                    "seo_description" => "Şık büyük beden giyim için açıklama",
                    "seo_keywords" => "Büyük Beden, moda, giyim",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "21",
                    "name" => "İç Giyim & Uyku Giyim",
                    "sub_category_id" => "2",
                    "seo_link" => "ic-giyim-uyku-giyim-2",
                    "seo_title" => "İç Giyim & Uyku Giyim",
                    "seo_description" => "Rahat iç giyim ve uyku giyim ürünleri için açıklama",
                    "seo_keywords" => "İç Giyim, Uyku Giyim, moda, giyim",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "22",
                    "name" => "Tesettür Giyim",
                    "sub_category_id" => "2",
                    "seo_link" => "tesettur-giyim",
                    "seo_title" => "Tesettür Giyim",
                    "seo_description" => "Şık ve rahat tesettür giyim ürünleri için açıklama",
                    "seo_keywords" => "Tesettür Giyim, moda, giyim",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "23",
                    "name" => "Büyük Beden",
                    "sub_category_id" => "2",
                    "seo_link" => "buyuk-beden-2",
                    "seo_title" => "Büyük Beden",
                    "seo_description" => "Şık büyük beden giyim için açıklama",
                    "seo_keywords" => "Büyük Beden, moda, giyim",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "24",
                    "name" => "Pantolon & Tayt",
                    "sub_category_id" => "2",
                    "seo_link" => "pantolon-tayt",
                    "seo_title" => "Pantolon & Tayt",
                    "seo_description" => "Rahat pantolon ve tayt ürünleri için açıklama",
                    "seo_keywords" => "Pantolon, Tayt, moda, giyim",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "25",
                    "name" => "Etek",
                    "sub_category_id" => "2",
                    "seo_link" => "etek",
                    "seo_title" => "Etek",
                    "seo_description" => "Şık etek modelleri için açıklama",
                    "seo_keywords" => "Etek, moda, giyim",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "26",
                    "name" => "Mayo, Bikini, Pareo",
                    "sub_category_id" => "2",
                    "seo_link" => "mayo-bikini-pareo",
                    "seo_title" => "Mayo, Bikini, Pareo",
                    "seo_description" => "Trend mayo, bikini ve pareo modelleri için açıklama",
                    "seo_keywords" => "Mayo, Bikini, Pareo, moda, giyim",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "27",
                    "name" => "Eşofman & Sweatshirt",
                    "sub_category_id" => "2",
                    "seo_link" => "esofman-sweatshirt-2",
                    "seo_title" => "Eşofman & Sweatshirt",
                    "seo_description" => "Rahat eşofman ve sweatshirt modelleri için açıklama",
                    "seo_keywords" => "Eşofman, Sweatshirt, moda, giyim",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "28",
                    "name" => "Cep Telefonu",
                    "sub_category_id" => "6",
                    "seo_link" => "cep-telefonu",
                    "seo_title" => "Cep Telefonu",
                    "seo_description" => "En yeni cep telefonu modelleri için açıklama",
                    "seo_keywords" => "Cep Telefonu, teknoloji, telefon",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "29",
                    "name" => "Cep Telefonu Aksesuarları",
                    "sub_category_id" => "6",
                    "seo_link" => "cep-telefonu-aksesuarlari",
                    "seo_title" => "Cep Telefonu Aksesuarları",
                    "seo_description" => "Cep telefonu aksesuarları için açıklama",
                    "seo_keywords" => "Cep Telefonu Aksesuarları, telefon aksesuarları, teknoloji",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "30",
                    "name" => "Masaüstü",
                    "sub_category_id" => "7",
                    "seo_link" => "masaustu",
                    "seo_title" => "Masaüstü",
                    "seo_description" => "Yüksek performanslı masaüstü bilgisayarlar için açıklama",
                    "seo_keywords" => "Masaüstü, bilgisayar, teknoloji",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "31",
                    "name" => "Notebook",
                    "sub_category_id" => "7",
                    "seo_link" => "notebook",
                    "seo_title" => "Notebook",
                    "seo_description" => "Hafif ve taşınabilir notebook bilgisayarlar için açıklama",
                    "seo_keywords" => "Notebook, laptop, bilgisayar, teknoloji",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "32",
                    "name" => "Aksesuarlar",
                    "sub_category_id" => "7",
                    "seo_link" => "aksesuarlar-2",
                    "seo_title" => "Aksesuarlar",
                    "seo_description" => "Ev aksesuarları için geniş seçenekler",
                    "seo_keywords" => "Ev aksesuarları, dekorasyon, pratik ürünler",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "33",
                    "name" => "LED TV",
                    "sub_category_id" => "8",
                    "seo_link" => "led-tv",
                    "seo_title" => "LED TV",
                    "seo_description" => "Yüksek çözünürlüklü LED TV modelleri için açıklama",
                    "seo_keywords" => "LED TV, televizyon, teknoloji, görüntü",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "34",
                    "name" => "Süpürge",
                    "sub_category_id" => "9",
                    "seo_link" => "supurge",
                    "seo_title" => "Süpürge",
                    "seo_description" => "Yüksek performanslı süpürge modelleri için açıklama",
                    "seo_keywords" => "Süpürge, temizlik, ev aletleri",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "35",
                    "name" => "Mutfak Gereçleri",
                    "sub_category_id" => "9",
                    "seo_link" => "mutfak-gerecleri",
                    "seo_title" => "Mutfak Gereçleri",
                    "seo_description" => "Mutfakta kullanılan pratik gereçler için açıklama",
                    "seo_keywords" => "Mutfak Gereçleri, mutfak aletleri, yemek pişirme",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "36",
                    "name" => "Çamaşır Makineleri",
                    "sub_category_id" => "10",
                    "seo_link" => "camasir-makineleri",
                    "seo_title" => "Çamaşır Makineleri",
                    "seo_description" => "Etkili ve enerji tasarruflu çamaşır makineleri için açıklama",
                    "seo_keywords" => "Çamaşır Makineleri, çamaşır yıkama, ev aletleri",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "37",
                    "name" => "Fotoğraf Makinesi",
                    "sub_category_id" => "11",
                    "seo_link" => "fotograf-makinesi",
                    "seo_title" => "Fotoğraf Makinesi",
                    "seo_description" => "Yüksek çözünürlüklü fotoğraf makineleri için açıklama",
                    "seo_keywords" => "Fotoğraf Makinesi, dijital fotoğraf makineleri, fotoğrafçılık",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "38",
                    "name" => "Kameralar",
                    "sub_category_id" => "11",
                    "seo_link" => "kameralar",
                    "seo_title" => "Kameralar",
                    "seo_description" => "Yüksek kaliteli kameralar için açıklama",
                    "seo_keywords" => "Kameralar, video kameralar, güvenlik kameraları",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "39",
                    "name" => "Dolap & Masa",
                    "sub_category_id" => "12",
                    "seo_link" => "dolap-masa",
                    "seo_title" => "Dolap & Masa",
                    "seo_description" => "Şık ve dayanıklı dolap ve masa modelleri için açıklama",
                    "seo_keywords" => "Dolap, Masa, mobilya, ev dekorasyonu",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "40",
                    "name" => "Dekorasyon",
                    "sub_category_id" => "13",
                    "seo_link" => "dekorasyon",
                    "seo_title" => "Dekorasyon",
                    "seo_description" => "Ev dekorasyonu için trendy ve şık ürünler",
                    "seo_keywords" => "Dekorasyon, ev dekorasyonu, iç mekan tasarımı",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "41",
                    "name" => "Aydınlatma",
                    "sub_category_id" => "13",
                    "seo_link" => "aydinlatma",
                    "seo_title" => "Aydınlatma",
                    "seo_description" => "Ev aydınlatması için modern ve estetik aydınlatma ürünleri",
                    "seo_keywords" => "Aydınlatma, lambalar, iç mekan aydınlatması",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "42",
                    "name" => "Mutfak Gereçleri",
                    "sub_category_id" => "15",
                    "seo_link" => "mutfak-gerecleri",
                    "seo_title" => "Mutfak Gereçleri",
                    "seo_description" => "Mutfakta kullanabileceğiniz pratik ve dayanıklı gereçler",
                    "seo_keywords" => "Mutfak Gereçleri, mutfak eşyaları, mutfak malzemeleri",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "43",
                    "name" => "Halı",
                    "sub_category_id" => "14",
                    "seo_link" => "hali",
                    "seo_title" => "Halı",
                    "seo_description" => "Ev dekorasyonunu tamamlayan şık ve kaliteli halı modelleri",
                    "seo_keywords" => "Halı, ev halısı, kilim, paspas",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "44",
                    "name" => "Perde",
                    "sub_category_id" => "14",
                    "seo_link" => "perde",
                    "seo_title" => "Perde",
                    "seo_description" => "Evde kullanabileceğiniz modern ve estetik perdeler",
                    "seo_keywords" => "Perde, stor perde, perde modelleri",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "45",
                    "name" => "Banyo Mobilyası",
                    "sub_category_id" => "16",
                    "seo_link" => "banyo-mobilyasi",
                    "seo_title" => "Banyo Mobilyası",
                    "seo_description" => "Banyonuz için şık ve kullanışlı mobilya seçenekleri",
                    "seo_keywords" => "Banyo Mobilyası, banyo dolabı, banyo rafı",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "46",
                    "name" => "Musluk Bataryası",
                    "sub_category_id" => "16",
                    "seo_link" => "musluk-bataryasi",
                    "seo_title" => "Musluk Bataryası",
                    "seo_description" => "Banyo ve mutfak lavaboları için şık ve dayanıklı musluk bataryaları",
                    "seo_keywords" => "Musluk Bataryası, lavabo bataryası, banyo bataryası, mutfak bataryası",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "47",
                    "name" => "Elektrikli El Aletleri",
                    "sub_category_id" => "17",
                    "seo_link" => "elektrikli-el-aletleri",
                    "seo_title" => "Elektrikli El Aletleri",
                    "seo_description" => "Ev ve işyeri için gerekli olan çeşitli elektrikli el aletleri",
                    "seo_keywords" => "Elektrikli El Aletleri, matkap, kesici, taşlama makinesi",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "48",
                    "name" => "Kedi",
                    "sub_category_id" => "18",
                    "seo_link" => "kedi",
                    "seo_title" => "Kedi Ürünleri",
                    "seo_description" => "Kediniz için gerekli olan oyuncaklar, mama ve bakım ürünleri",
                    "seo_keywords" => "Kedi Ürünleri, kedi oyuncakları, kedi maması, kedi bakım ürünleri",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "49",
                    "name" => "Köpek",
                    "sub_category_id" => "18",
                    "seo_link" => "kopek",
                    "seo_title" => "Köpek Ürünleri",
                    "seo_description" => "Köpeğiniz için gerekli olan oyuncaklar, mama ve bakım ürünleri",
                    "seo_keywords" => "Köpek Ürünleri, köpek oyuncakları, köpek maması, köpek bakım ürünleri",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "50",
                    "name" => "Kırtasiye Ürünleri",
                    "sub_category_id" => "19",
                    "seo_link" => "kirtasiye-urunleri",
                    "seo_title" => "Kırtasiye Ürünleri",
                    "seo_description" => "Ofis ve okul ihtiyaçlarınız için kırtasiye ürünleri",
                    "seo_keywords" => "Kırtasiye Ürünleri, defter, kalem, silgi, cetvel",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "51",
                    "name" => "Ofis Teknolojileri",
                    "sub_category_id" => "19",
                    "seo_link" => "ofis-teknolojileri",
                    "seo_title" => "Ofis Teknolojileri",
                    "seo_description" => "Ofis için gerekli olan teknolojik ürünler ve aksesuarlar",
                    "seo_keywords" => "Ofis Teknolojileri, bilgisayar, yazıcı, tarayıcı, ofis aksesuarları",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "52",
                    "name" => "Genel Market Ürünleri",
                    "sub_category_id" => "20",
                    "seo_link" => "genel-market-urunleri",
                    "seo_title" => "Genel Market Ürünleri",
                    "seo_description" => "Günlük ihtiyaçlarınız için genel market ürünleri",
                    "seo_keywords" => "Genel Market Ürünleri, temel gıda, temizlik ürünleri, günlük ihtiyaçlar",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "53",
                    "name" => "Bebek Bezi",
                    "sub_category_id" => "21",
                    "seo_link" => "bebek-bezi",
                    "seo_title" => "Bebek Bezi",
                    "seo_description" => "Bebek bezleri, bebek bakımı için ideal ürünler",
                    "seo_keywords" => "Bebek Bezi, bebek bezi markaları, bebek bakım ürünleri",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "54",
                    "name" => "Islak Mendil",
                    "sub_category_id" => "21",
                    "seo_link" => "islak-mendil",
                    "seo_title" => "Islak Mendil",
                    "seo_description" => "Islak mendiller, pratik temizlik için kullanışlı ürünler",
                    "seo_keywords" => "Islak Mendil, ıslak temizlik, bebek temizlik ürünleri",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "55",
                    "name" => "Kız Bebek",
                    "sub_category_id" => "22",
                    "seo_link" => "kiz-bebek",
                    "seo_title" => "Kız Bebek Ürünleri",
                    "seo_description" => "Kız bebekler için özel tasarlanmış ürünler",
                    "seo_keywords" => "Kız Bebek Ürünleri, bebek kıyafetleri, bebek oyuncakları",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "56",
                    "name" => "Erkek Bebek",
                    "sub_category_id" => "22",
                    "seo_link" => "erkek-bebek",
                    "seo_title" => "Erkek Bebek Ürünleri",
                    "seo_description" => "Erkek bebekler için özel tasarlanmış ürünler",
                    "seo_keywords" => "Erkek Bebek Ürünleri, bebek kıyafetleri, bebek oyuncakları",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "57",
                    "name" => "Hamile Kıyafetleri",
                    "sub_category_id" => "23",
                    "seo_link" => "hamile-kiyafetleri",
                    "seo_title" => "Hamile Kıyafetleri",
                    "seo_description" => "Rahat ve şık hamile kıyafetleri",
                    "seo_keywords" => "Hamile Kıyafetleri, hamile giyim, hamile elbiseleri",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "58",
                    "name" => "Bebek Arabası",
                    "sub_category_id" => "24",
                    "seo_link" => "bebek-arabasi",
                    "seo_title" => "Bebek Arabası",
                    "seo_description" => "Konforlu ve güvenli bebek arabaları",
                    "seo_keywords" => "Bebek Arabası, bebek taşıma, bebek arabaları markaları",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "59",
                    "name" => "Mama Sandalyesi",
                    "sub_category_id" => "25",
                    "seo_link" => "mama-sandalyesi",
                    "seo_title" => "Mama Sandalyesi",
                    "seo_description" => "Pratik ve kullanışlı mama sandalyeleri",
                    "seo_keywords" => "Mama Sandalyesi, bebek beslenme, mama sandalyesi markaları",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "60",
                    "name" => "Parfümler",
                    "sub_category_id" => "26",
                    "seo_link" => "parfumler",
                    "seo_title" => "Parfümler",
                    "seo_description" => "Farklı ve kaliteli parfüm seçenekleri",
                    "seo_keywords" => "Parfümler, parfüm markaları, parfüm çeşitleri",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "61",
                    "name" => "Tıraş Makineleri",
                    "sub_category_id" => "27",
                    "seo_link" => "tiras-makineleri",
                    "seo_title" => "Tıraş Makineleri",
                    "seo_description" => "Hassas ve etkili tıraş makineleri",
                    "seo_keywords" => "Tıraş Makineleri, tıraş makineleri markaları, tıraş makineleri çeşitleri",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "62",
                    "name" => "Yüz Bakımı",
                    "sub_category_id" => "28",
                    "seo_link" => "yuz-bakimi",
                    "seo_title" => "Yüz Bakımı",
                    "seo_description" => "Cilt sağlığı için özel yüz bakım ürünleri",
                    "seo_keywords" => "Yüz Bakımı, cilt bakımı, yüz bakım ürünleri",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "63",
                    "name" => "Makyaj Aksesuarları",
                    "sub_category_id" => "29",
                    "seo_link" => "makyaj-aksesuarlari",
                    "seo_title" => "Makyaj Aksesuarları",
                    "seo_description" => "Makyaj için gerekli aksesuarlar ve malzemeler",
                    "seo_keywords" => "Makyaj Aksesuarları, makyaj fırçaları, makyaj süngeri",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "64",
                    "name" => "Saç Bakım Ürünleri",
                    "sub_category_id" => "27",
                    "seo_link" => "sac-bakim-urunleri",
                    "seo_title" => "Saç Bakım Ürünleri",
                    "seo_description" => "Saç sağlığı ve güzelliği için özel saç bakım ürünleri",
                    "seo_keywords" => "Saç Bakım Ürünleri, saç bakımı, şampuan, saç kremi",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "65",
                    "name" => "Hastane Ekipmanları",
                    "sub_category_id" => "30",
                    "seo_link" => "hastane-ekipmanlari",
                    "seo_title" => "Hastane Ekipmanları",
                    "seo_description" => "Sağlık kurumları ve hastaneler için özel ekipmanlar",
                    "seo_keywords" => "Hastane Ekipmanları, tıbbi ekipman, hastane malzemeleri",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "66",
                    "name" => "Antibakteriyel Jel & Dezenfektan",
                    "sub_category_id" => "30",
                    "seo_link" => "antibakteriyel-jel-dezenfektan",
                    "seo_title" => "Antibakteriyel Jel & Dezenfektan",
                    "seo_description" => "Mikroplardan korunmak için güçlü dezenfektanlar",
                    "seo_keywords" => "Antibakteriyel Jel, Dezenfektan, el dezenfektanı, antibakteriyel ürünler",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "67",
                    "name" => "Epilasyon & Ağda",
                    "sub_category_id" => "31",
                    "seo_link" => "epilasyon-agda",
                    "seo_title" => "Epilasyon & Ağda",
                    "seo_description" => "Uzun süreli tüylerden kurtulmanın en etkili yolları",
                    "seo_keywords" => "Epilasyon, Ağda, cilt bakımı, tüy alma",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "68",
                    "name" => "Ağız Bakım",
                    "sub_category_id" => "32",
                    "seo_link" => "agiz-bakim",
                    "seo_title" => "Ağız Bakım",
                    "seo_description" => "Diş sağlığı için gerekli ağız bakım ürünleri",
                    "seo_keywords" => "Ağız Bakım, diş fırçası, diş macunu, diş sağlığı",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "69",
                    "name" => "Erkek Kol Saatleri",
                    "sub_category_id" => "33",
                    "seo_link" => "erkek-kol-saatleri",
                    "seo_title" => "Erkek Kol Saatleri",
                    "seo_description" => "Şıklığı tamamlayan erkek kol saatleri",
                    "seo_keywords" => "Erkek Kol Saatleri, saat, erkek saat modelleri",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "70",
                    "name" => "Kadın Kol Saatleri",
                    "sub_category_id" => "33",
                    "seo_link" => "kadin-kol-saatleri",
                    "seo_title" => "Kadın Kol Saatleri",
                    "seo_description" => "Zarif ve şık kadın kol saatleri",
                    "seo_keywords" => "Kadın Kol Saatleri, kadın saat, kol saati modelleri",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "71",
                    "name" => "Erkek Takı",
                    "sub_category_id" => "34",
                    "seo_link" => "erkek-taki",
                    "seo_title" => "Erkek Takı",
                    "seo_description" => "Erkekler için özel takı ve aksesuarlar",
                    "seo_keywords" => "Erkek Takı, erkek bilezik, erkek kolye, erkek aksesuar",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "72",
                    "name" => "Kadın Takı",
                    "sub_category_id" => "34",
                    "seo_link" => "kadin-taki",
                    "seo_title" => "Kadın Takı",
                    "seo_description" => "Kadınların zarafetini tamamlayan takılar",
                    "seo_keywords" => "Kadın Takı, kolye, bilezik, küpe, takı setleri",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "73",
                    "name" => "Spor Ayakkabı",
                    "sub_category_id" => "35",
                    "seo_link" => "spor-ayakkabi",
                    "seo_title" => "Spor Ayakkabı",
                    "seo_description" => "Rahat ve şık spor ayakkabı modelleri",
                    "seo_keywords" => "Spor Ayakkabı, koşu ayakkabısı, spor ayakkabı modelleri",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "74",
                    "name" => "Spor Kıyafetleri",
                    "sub_category_id" => "35",
                    "seo_link" => "spor-kiyafetleri",
                    "seo_title" => "Spor Kıyafetleri",
                    "seo_description" => "Rahat ve fonksiyonel spor kıyafetleri",
                    "seo_keywords" => "Spor Kıyafetleri, spor giyim, antrenman kıyafetleri",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "75",
                    "name" => "Spor Aksesuarları",
                    "sub_category_id" => "35",
                    "seo_link" => "spor-aksesuarlari",
                    "seo_title" => "Spor Aksesuarları",
                    "seo_description" => "Spor aktiviteleri için gerekli aksesuarlar",
                    "seo_keywords" => "Spor Aksesuarları, spor şapka, spor eldiven, su şişesi",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "76",
                    "name" => "Mont",
                    "sub_category_id" => "36",
                    "seo_link" => "mont",
                    "seo_title" => "Mont",
                    "seo_description" => "Soğuk havalarda sizi sıcak tutacak mont modelleri",
                    "seo_keywords" => "Mont, kaban, dış giyim, kışlık mont",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "77",
                    "name" => "Outdoor Ayakkabı",
                    "sub_category_id" => "36",
                    "seo_link" => "outdoor-ayakkabi",
                    "seo_title" => "Outdoor Ayakkabı",
                    "seo_description" => "Doğa yürüyüşleri ve outdoor aktiviteler için özel üretilmiş ayakkabılar",
                    "seo_keywords" => "Outdoor Ayakkabı, doğa yürüyüş ayakkabısı, outdoor botlar",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "78",
                    "name" => "Edebiyat",
                    "sub_category_id" => "37",
                    "seo_link" => "edebiyat",
                    "seo_title" => "Edebiyat",
                    "seo_description" => "Edebiyat eserleri, kitap incelemeleri ve yazarlar hakkında bilgiler",
                    "seo_keywords" => "Edebiyat, edebi eserler, kitap incelemeleri, yazarlar",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "79",
                    "name" => "Eğitim",
                    "sub_category_id" => "37",
                    "seo_link" => "egitim",
                    "seo_title" => "Eğitim",
                    "seo_description" => "Eğitim materyalleri, ders notları ve eğitim programları",
                    "seo_keywords" => "Eğitim, ders notları, eğitim materyalleri, online eğitim",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "80",
                    "name" => "Çocuk",
                    "sub_category_id" => "37",
                    "seo_link" => "cocuk",
                    "seo_title" => "Çocuk",
                    "seo_description" => "Çocuklar için oyuncaklar, kıyafetler ve eğitici materyaller",
                    "seo_keywords" => "Çocuk, oyuncaklar, çocuk giyim, eğitici oyunlar",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "81",
                    "name" => "Müzik Aletleri",
                    "sub_category_id" => "38",
                    "seo_link" => "muzik-aletleri",
                    "seo_title" => "Müzik Aletleri",
                    "seo_description" => "Müzik aletleri, enstrümanlar ve müzik aksesuarları",
                    "seo_keywords" => "Müzik Aletleri, enstrümanlar, müzik aksesuarları, enstrüman satışı",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "82",
                    "name" => "Müzik Aleti Aksesuarları",
                    "sub_category_id" => "38",
                    "seo_link" => "muzik-aleti-aksesuarlari",
                    "seo_title" => "Müzik Aleti Aksesuarları",
                    "seo_description" => "Müzik aletlerine yönelik aksesuarlar, teller, kemikler, bağlantı parçaları",
                    "seo_keywords" => "Müzik Aleti Aksesuarları, müzik aleti parçaları, alet tamir malzemeleri",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "83",
                    "name" => "Yabancı Film",
                    "sub_category_id" => "39",
                    "seo_link" => "yabanci-film",
                    "seo_title" => "Yabancı Film",
                    "seo_description" => "Yabancı sinema filmleri, en son çıkan yabancı filmler ve film incelemeleri",
                    "seo_keywords" => "Yabancı Film, yabancı sinema, film incelemeleri, en son çıkan filmler",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "84",
                    "name" => "Yerli Film",
                    "sub_category_id" => "39",
                    "seo_link" => "yerli-film",
                    "seo_title" => "Yerli Film",
                    "seo_description" => "Yerli sinema filmleri, en son çıkan yerli filmler ve film incelemeleri",
                    "seo_keywords" => "Yerli Film, yerli sinema, film incelemeleri, en son çıkan filmler",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "85",
                    "name" => "Maketler",
                    "sub_category_id" => "40",
                    "seo_link" => "maketler",
                    "seo_title" => "Maketler",
                    "seo_description" => "Maket yapımı için gerekli malzemeler, maket setleri ve yapım rehberleri",
                    "seo_keywords" => "Maketler, maket yapımı, maket malzemeleri, maket setleri",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "86",
                    "name" => "Kutu Oyunlar",
                    "sub_category_id" => "40",
                    "seo_link" => "kutu-oyunlar",
                    "seo_title" => "Kutu Oyunlar",
                    "seo_description" => "Strateji, bilgi ve eğlenceye dayalı kutu oyunları, masa oyunları",
                    "seo_keywords" => "Kutu Oyunlar, strateji oyunları, masa oyunları, eğlenceli kutu oyunları",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "87",
                    "name" => "Lastik & Jantlar",
                    "sub_category_id" => "42",
                    "seo_link" => "lastik-jantlar",
                    "seo_title" => "Lastik & Jantlar",
                    "seo_description" => "Araç lastikleri, jantlar ve lastik-jant setleri, en iyi markalar ve modeller",
                    "seo_keywords" => "Lastik & Jantlar, araç lastikleri, jantlar, lastik-jant setleri",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "88",
                    "name" => "Oto Aksesuar Ürünleri",
                    "sub_category_id" => "42",
                    "seo_link" => "oto-aksesuar-urunleri",
                    "seo_title" => "Oto Aksesuar Ürünleri",
                    "seo_description" => "Araç içi ve dışı aksesuar ürünleri, dekoratif ve pratik oto aksesuarlar",
                    "seo_keywords" => "Oto Aksesuar Ürünleri, araç aksesuarları, oto dekorasyon, araç içi aksesuarlar",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "89",
                    "name" => "Oto Yedek Parçalar",
                    "sub_category_id" => "42",
                    "seo_link" => "oto-yedek-parcalar",
                    "seo_title" => "Oto Yedek Parçalar",
                    "seo_description" => "Oto yedek parça ürünleri, araç bakım ve onarımları için gerekli yedek parçalar",
                    "seo_keywords" => "Oto Yedek Parçalar, araç yedek parçaları, otomobil bakım, araç onarımları",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "90",
                    "name" => "Motosiklet Aksesuarları",
                    "sub_category_id" => "43",
                    "seo_link" => "motosiklet-aksesuarlari",
                    "seo_title" => "Motosiklet Aksesuarları",
                    "seo_description" => "Motosiklet aksesuar ürünleri, sürüş güvenliği ve konforu için gerekli ekipmanlar",
                    "seo_keywords" => "Motosiklet Aksesuarları, motosiklet ekipmanları, motosiklet güvenliği, sürüş aksesuarları",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ],
                [
                    "id" => "91",
                    "name" => "Sinema Biletleri",
                    "sub_category_id" => "41",
                    "seo_link" => "sinema-biletleri",
                    "seo_title" => "Sinema Biletleri",
                    "seo_description" => "En son çıkan filmler için sinema biletleri, vizyondaki filmler ve seanslar",
                    "seo_keywords" => "Sinema Biletleri, sinema filmleri, sinema seansları, vizyondaki filmler",
                    "status" => "1",
                    "created_at" => "1/10/2023 20:37:46",
                    "updated_at" => "1/10/2023 20:37:46"
                ]
            ];

        SubSubCategory::query()->insert($defaultData);
    }
}
